title: Phantasus 
repository: ctlab/phantasus

plugins:
  #- jekyll-remote-theme
  - jekyll-spaceship

    # remote_theme: 
    #   just-the-docs/just-the-docs@main

theme: just-the-docs

kramdown:
  toc_levels: "1,2,3"

aux_links:
  "Phantasus on GitHub":
      - "https://github.com/ctlab/phantasus"

ga_tracking: G-P50BJBHWD2
ga_tracking_anonymize_ip: true
